### ISSUE TITLE
Audit Report  - Date Amanedment

### ISSUE THREAD

**Issue by LahiruBa** [pathum-kalhan/Fleet-management-UI#6]
Audit report does not show any data for 02nd of 2020 although there are data in the system.

![image](https://user-images.githubusercontent.com/37596584/71646302-3b8a5380-2d0c-11ea-812a-b1c27bedbe44.png)

![image](https://user-images.githubusercontent.com/37596584/71646303-4a710600-2d0c-11ea-8b89-59b865e7af17.png)

**Comment by pathum-kalhan** [comment]
@LahiruBa  I checked this and works fine in my one. Need to check with you.

**Comment by LahiruBa** [comment]
Now it's working that day date is data is not visible although it is in the audit
